In [142]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [143]:
dataset = pd.read_csv('Data.csv')
np.set_printoptions(precision=2,suppress=True)
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [144]:
dataset.shape

(10, 4)

In [145]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,3].values

In [146]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [147]:
print(X.shape)

(10, 3)


In [148]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'], dtype=object)

In [149]:
print(y.shape)

(10,)


In [150]:
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values='NaN',strategy='mean',axis=0)
imputer = imputer.fit(X[:,1:])
X[:,1:] = imputer.transform(X[:,1:])
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [151]:
from sklearn.preprocessing import LabelEncoder
label_encoderX = LabelEncoder()
X[:,0] = label_encoderX.fit_transform(X[:,0])
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [152]:
label_encoder_y = LabelEncoder()
y = label_encoder_y.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [153]:
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder = OneHotEncoder(categorical_features=[0])
X = one_hot_encoder.fit_transform(X).toarray()
X

array([[     1.  ,      0.  ,      0.  ,     44.  ,  72000.  ],
       [     0.  ,      0.  ,      1.  ,     27.  ,  48000.  ],
       [     0.  ,      1.  ,      0.  ,     30.  ,  54000.  ],
       [     0.  ,      0.  ,      1.  ,     38.  ,  61000.  ],
       [     0.  ,      1.  ,      0.  ,     40.  ,  63777.78],
       [     1.  ,      0.  ,      0.  ,     35.  ,  58000.  ],
       [     0.  ,      0.  ,      1.  ,     38.78,  52000.  ],
       [     1.  ,      0.  ,      0.  ,     48.  ,  79000.  ],
       [     0.  ,      1.  ,      0.  ,     50.  ,  83000.  ],
       [     1.  ,      0.  ,      0.  ,     37.  ,  67000.  ]])

In [154]:
from sklearn.cross_validation import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [155]:
X_train

array([[     0.  ,      1.  ,      0.  ,     40.  ,  63777.78],
       [     1.  ,      0.  ,      0.  ,     37.  ,  67000.  ],
       [     0.  ,      0.  ,      1.  ,     27.  ,  48000.  ],
       [     0.  ,      0.  ,      1.  ,     38.78,  52000.  ],
       [     1.  ,      0.  ,      0.  ,     48.  ,  79000.  ],
       [     0.  ,      0.  ,      1.  ,     38.  ,  61000.  ],
       [     1.  ,      0.  ,      0.  ,     44.  ,  72000.  ],
       [     1.  ,      0.  ,      0.  ,     35.  ,  58000.  ]])

In [156]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [157]:
X_test

array([[     0.,      1.,      0.,     30.,  54000.],
       [     0.,      1.,      0.,     50.,  83000.]])

In [158]:
y_test

array([0, 0])

In [159]:
from sklearn.preprocessing import StandardScaler
standard_scaler = StandardScaler()

X_train = standard_scaler.fit_transform(X_train)
X_test = standard_scaler.transform(X_test)

In [160]:
X_train

array([[-1.  ,  2.65, -0.77,  0.26,  0.12],
       [ 1.  , -0.38, -0.77, -0.25,  0.46],
       [-1.  , -0.38,  1.29, -1.98, -1.53],
       [-1.  , -0.38,  1.29,  0.05, -1.11],
       [ 1.  , -0.38, -0.77,  1.64,  1.72],
       [-1.  , -0.38,  1.29, -0.08, -0.17],
       [ 1.  , -0.38, -0.77,  0.95,  0.99],
       [ 1.  , -0.38, -0.77, -0.6 , -0.48]])

In [161]:
X_test

array([[-1.  ,  2.65, -0.77, -1.46, -0.9 ],
       [-1.  ,  2.65, -0.77,  1.98,  2.14]])